title: 简历 - 郑子涛

aboutme:
  name: 郑子涛
  sex: 男
  age: 22
  email: l.seeriana@gmail.com
  phone: 13028827756
  github: https://github.com/zztriana
  city: 深圳
  job: Web后端开发工程师
  edu: 中专

update: 2021年01月13日